name: Suspension Yoga
favicon: null
layout_spectrum: 0.4909254133235663
typography_spectrum: 0.393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef9ff'
    - '#000000'
    - '#f26f37'
    - '#abb06d'
    - '#1375d2'
  brandStrength: 1
  lightness: 0
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
