name: Suspension Yoga
favicon: null
layout_spectrum: 0.76108
typography_spectrum: 0.393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eb363d'
    - '#f16f36'
    - '#83bfe7'
    - '#4f5a0b'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
